spring.application.name=SpringLabRestProj05-EmployeeManagementREST-API

#database properties

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl2
spring.datasource.username=shreyash18
spring.datasource.password=nit50

#JPA Properties

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true

#Embedded server 
server.port=4041
server.servlet.context-path=/springLabProj05